site_name: 'node-app-ai-backend-test-2'
site_description: 'Main documentation for the node-app-ai-backend-test-2'
repo_url: https://github.com/ArjunKumarNair/node-app-ai-backend-test-2
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - What is Backstage?: 'docs/index.md'